name: Keep Render awake

on:
  schedule:
    - cron: "*/5 * * * *"   # ogni 5 minuti (CRON in UTC)
  workflow_dispatch:         # ti permette di lanciarlo a mano

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping homepage
        env:
          URL: https://telegram-bot-pqkg.onrender.com/
        run: |
          # tenta 3 volte, non fallire il job se momentaneamente giù
          for i in 1 2 3; do
            if curl -fsS --max-time 10 "$URL" -o /dev/null; then
              echo "OK: ping riuscito"
              exit 0
            fi
            echo "Tentativo $i fallito, riprovo..."
            sleep 5
          done
          echo "Warning: non sono riuscito a pingare, ma continuo senza fallire."
          exit 0

